#!/bin/bash

# Watchdog script to gracefully restart Gunicorn workers if the service is idle.

# --- Configuration ---
# Path to the heartbeat file updated by the FastAPI middleware.
HEARTBEAT_FILE=${HEARTBEAT_FILE:-/tmp/mt_photos_ai.heartbeat}
# Path to the PID file generated by Gunicorn.
PID_FILE=${PID_FILE:-/tmp/gunicorn.pid}
# Idle time in seconds. If the service is inactive for this long, it will be restarted.
# Default is 1800 seconds (30 minutes).
IDLE_SECONDS=${IDLE_SECONDS:-1800}

# --- Logic ---

# 1. Check if the Gunicorn process is running by looking for the PID file.
if [ ! -f "$PID_FILE" ]; then
  # Gunicorn is not running, so there's nothing to do.
  # echo "Watchdog: Gunicorn PID file not found. Exiting."
  exit 0
fi

# 2. Check if the heartbeat file exists.
if [ ! -f "$HEARTBEAT_FILE" ]; then
  # If the service has started but hasn't received any requests yet,
  # the file might not exist. We can create it and exit for the next check.
  echo "Watchdog: Heartbeat file not found. Creating it."
  touch "$HEARTBEAT_FILE"
  exit 0
fi

# 3. Calculate the time since the last request.
LAST_ACTIVE_TIMESTAMP=$(stat -c %Y "$HEARTBEAT_FILE")
CURRENT_TIMESTAMP=$(date +%s)
SECONDS_SINCE_ACTIVE=$((CURRENT_TIMESTAMP - LAST_ACTIVE_TIMESTAMP))

echo "Watchdog: Service was last active $SECONDS_SINCE_ACTIVE seconds ago."

# 4. If idle time exceeds the threshold, send the HUP signal to Gunicorn.
if [ "$SECONDS_SINCE_ACTIVE" -gt "$IDLE_SECONDS" ]; then
  GUNICORN_PID=$(cat "$PID_FILE")
  echo "Watchdog: Service has been idle for over $IDLE_SECONDS seconds."
  echo "Watchdog: Sending SIGHUP to Gunicorn master process (PID: $GUNICORN_PID) to restart workers."
  
  # SIGHUP tells Gunicorn to gracefully restart all worker processes.
  # This reloads the application and releases memory without downtime.
  kill -HUP "$GUNICORN_PID"
  
  # After restarting, touch the heartbeat file again to reset the timer.
  touch "$HEARTBEAT_FILE"
  echo "Watchdog: Restart signal sent. Timer reset."
fi
